name: Build and Test D.A.R.K Launcher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests psutil ttkbootstrap colorama pillow pyperclip python-dotenv

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=120 --ignore=E402,W503

      - name: Install Windows SDK
        run: |
          choco install windows-sdk-10-version-2004-all -y
        shell: powershell
        env:
          chocolateyUseWindowsCompression: 'false'

      - name: Create .env file
        run: |
          echo UPLOAD_URL=https://example.com/upload >> .env
          echo UPLOAD_TOKEN=dummy-token >> .env
          echo SIGNTOOL_PATH="C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" >> .env
          echo CERT_FILE=certificate.pfx >> .env
          echo CERT_PASSWORD=dummy-password >> .env
          echo DIST_PATH=dist >> .env
          echo BACKUP_PATH=backup >> .env
          echo EXE_NAME="D.A.R.K Launcher.exe" >> .env
          echo MAX_BACKUPS=10 >> .env

      - name: Create Dummy Certificate
        run: |
          echo "Dummy certificate content" > certificate.pfx

      - name: Ensure icon.ico exists
        run: |
          if not exist icon.ico echo "Dummy icon" > icon.ico

      - name: Build with py2exp.py
        run: |
          python py2exp.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DARK-Launcher-Build
          path: dist/D.A.R.K Launcher.exe
        continue-on-error: true

      - name: Verify Build Output
        run: |
          if not exist "dist\D.A.R.K Launcher.exe" exit 1
          echo "Build successful: D.A.R.K Launcher.exe created"