name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests psutil ttkbootstrap colorama pillow pyperclip python-dotenv

      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=120 --ignore=E402,W503

      - name: Run Unit Tests
        run: |
          pytest tests/ -v
        continue-on-error: true

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🚨 Linting or Unit Test fail. Please check log!'
            })